config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  devise_for :user,path: 'patrie', controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}


  namespace :admin do
    root to:"homes#top"
    resources :posts
    resources :users
  end
  scope module: :user do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :posts do
      resources :comments, only: [:create,:destroy]
      resource :likes, only: [:create, :destroy]
    end
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    resources :notifications,only: [:index,:destroy]
    resources :relationships
    resources :users
    get "/user/unsubscribe" => "users#unsubscribe"
    patch "/user/withdraw" => "users#withdraw"
  end
  get '/search' => 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :likes,dependent: :destroy
  has_many :follower,class_name:"Relationship",foreign_key:"follower_id",dependent: :destroy
  has_many :followed,class_name:"Relationship",foreign_key:"followed_id",dependent: :destroy

  has_many :following_user,through: :follower,source: :followed
  has_many :follower_user,through: :followed,source: :follower

  has_many :active_notifications,class_name: 'Notification',foreign_key: 'visitor_id',dependent: :destroy
  has_many :passive_notifications,class_name: 'Notification',foreign_key: 'visited_id',dependent: :destroy

  has_one_attached :profile_image
  

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/jinnbutu.png')
      profile_image.attach(io: File.open(file_path), filename: 'jinnbutu.png', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    following_user.include?(user)
  end

  def self.looks(search,word)
    if search == "perfect_match"
      @user = User.where("user_name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("user_name LIKE?","#{word}%")
    elsif search == "backword_mach"
      @user = User.where("user_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("user_name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?",current_user.id,id,'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  if@user.update(user_params)
    redirect_to admin_user_path
  else
    render:edit
  end
  end

  private

  def
    user_params
    params.require(:user).permit(:name,:user_name,:email,:is_deleted)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      flash[:success] = 'コメントしました'
      @post = @comment.post
      @post.create_notification_comment!(current_user, @comment.id)
      redirect_to @comment.post
    else
      render templete: 'posts/show'
    end  
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment,:post_id,:user_id,:content)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  before_action :authenticate_user!
  def top
  end

  def about
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id:post.id)
    like.save
    post.create_notification_like!(current_user)
    respond_to do |format|
      format.html {redirect_back(fallback_location: 'users/show')}
      format.js
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id:post.id)
    like.destroy
    redirect_to post_path(post)
  end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.passive_notifications
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  def new
    @post = Post.new
    @user =  current_user
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
  if @post.save
    flash[:success] = '投稿しました'
     redirect_to posts_path
  else
    render :new
  end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user.id)
    @comment = Comment.new
    @comments = @post.comments
    @likes = Like.where(user_id:current_user.id)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
  if@post.update(post_params)
    redirect_to post_path(@post)
  else
    render :edit
  end
  end

  def destroy
    @post = Post.find(params[:id])
  if  @post.destroy
    redirect_to posts_path
  else
    render :show
  end
  end

  def index
    @user =  current_user
    @posts = Post.all
    @feeds = Post.where(user_id:[current_user.id,*current_user.following_user]).page(params[:page]).per(3)
    @likes = Like.where(user_id:current_user.id)
  end

  def search
    if params[:keyword].present?
      @posts = Post.where('caption LIKE ?',"%#{params[:keyword]}%")
      @keyword = params[:keyword]
    else
      @posts = Post.all
    end
  end

  private

  def post_params
    params.require(:post).permit(:text,:user_id,:image)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user =  current_user
  end

  def create
    @user.create_notification_follow!(current_user)
    respond_to do |format|
      format.html {redirect_back(fallback_location: root_url)}
      format.js
    end
  end

  def follow
    current_user.follow(params[:id])
    redirect_to user_path
  end

  def unfollow
    current_user.unfollow(params[:id])
    redirect_to user_path
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
   #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  def customer_state
    @user = User.find_by(email: params[:user][:email])
  return if !@user
  if @user.valid_password?(params[:user][:password]) && !@user.is_deleted
  end
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user =  current_user
    @user = User.find(params[:id])
    @posts = @user.posts
    @likes = Like.where(user_id:current_user.id)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path(current_user.id)
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def unsubscribe
  end

  private

  def user_params
    params.require(:user).permit(:user_name,:profile_image,:intoduction,:name)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/likes_helper.rb
module User::LikesHelper
end

app/helpers/user/notifications_helper.rb
module User::NotificationsHelper
  def notification_form(notification)
    @visitor = notification.visitor
    @comment = nil
    @your_post = link_to 'あなたの投稿',post_path(notification),style:"font-weight: bold;"
    @visitor_comment = notification.comment_id
    case notification.action
      when "follow" then
        tag.a(notification.visitor.user_name,href:user_path(@visitor),style:"font-weight: bold;")+"があなたをフォローしました"
      when "like" then
        tag.a(notification.visitor.user_name,href:user_path(@visitor),style:"font-weight: bold;")+"が"+tag.a('あなたの投稿',href:post_path(notification.post_id),style:"font-weight: bold;")+"をいいねしました"
      when "comment" then
        tag.a(notification.visitor.user_name,href:user_path(@visitor),style:"font-weight: bold;")+"が"+tag.a('あなたの投稿',href:post_path(notification.post_id),style:"font-weight: bold;")+"にコメントしました"
    end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/user/users/edit.html.erb
<%= form_with model: @user,url: user_path,method: :patch do |f| %>
<div class="container">
  <div class="row">
    <div class="col-md-2 text-left">
      <%= link_to 'キャンセル',user_path(@user),class:"btn" %>
    </div>
    <div class="col-md-9 mx-auto text-center">
      <span><strong>プロフィールを編集</strong></span>
    </div>

    <div class="col-md-1">
      <%= f.submit '完了',class:"btn btn-primary" %>
    </div>
  </div>
  <div class="col-lg-10 offset-lg-1">
    <div class="row">
    </div>
  </div>

    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="row field">
          <p>
          <%= f.file_field:profile_image,accept:'image/*' do %>
          <%= image_tag @user.get_profile_image(100,100),class:'rounded-circle' %>
          <% end %>
          </p>
        </div>
        <div class="row field">
          <p>
          <%= f.text_field :user_name, style: "border: none" %>
          </p>
        </div>
        <hr>
        <div class="row field">
          <p><%= f.text_area :intoduction, style: "border: none",size:"50x10" %></p>
        </div>
        <div>
          <%= f.submit '変更を保存',class:'btn btn-sm btn-success' %>
          <%= link_to '退会する',user_unsubscribe_path,class:'btn btn-sm btn-danger' %>
        </div>
      </div>
    </div>
</div>
<% end %>

app/views/user/users/show.html.erb
<%= render "layouts/header" %>
<div class="container">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <%= image_tag @user.get_profile_image(80,80),class:'rounded-circle' %>
      <%= @user.user_name %>
      <div class="offset-8">
        <% if @user == current_user %>
        <%= link_to "プロフィールを編集",edit_user_path(@user),class:"btn btn-info" %>
        <% end %>
      </div>
      <p><%= @user.intoduction %></p>
      <hr>
    <div>
        <%= "#{@user.follower.count}" %>
        <%= link_to relationships_path,class:"btn" do %>
        フォロワー
        <% end %>
      <span></span>
      <%= "#{@user.followed.count}" %>
        <%= link_to relationships_path,class:"btn" do %>
        フォロー
        <% end %>
    </div>
    <hr>
    <% unless @user == current_user %>
      <% if current_user.following?(@user) %>
        <%= link_to 'フォローを外す',unfollow_path(@user.id),class:"btn btn-light text-info",method: :post %>
      <% else %>
        <%= link_to 'フォローする',follow_path(@user.id),class:"btn btn-info text-light",method: :post %>
      <% end %>
    <% end %>

    <ul class="text-center nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item w-50 bg-light">
    <a class="nav-link active link-text" id="post-tab" data-toggle="tab" href="#post" role="tab" aria-controls="post" aria-selected="true">投稿</a>
  </li>
  <li class="nav-item w-50 bg-light">
    <a class="nav-link link-text" id="like-tab" data-toggle="tab" href="#like" role="tab" aria-controls="like" aria-selected="false">いいね</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="post" role="tabpanel" aria-labelledby="post-tab">
    <% @posts.each do |posts| %>
      <p>
        <%= image_tag @user.get_profile_image(90,90),class:"rounded-circle" %>
      <%= @user.user_name %>
      </p>
      <%= link_to post_path(posts.id) do %>
      <%= image_tag posts.get_image,size:"500x400" %>
      <% end %>
        <% if posts.liked_by?(current_user) %>
        <p>
          <%= link_to post_likes_path(posts.id),method: :delete do %>
          <i class="fa-solid fa-heart"></i><%= posts.likes.count %>
          <% end %>
          </p>
        <% else %>
          <p>
          <%= link_to post_likes_path(posts.id),method: :post do %>
          <i class="fa-regular fa-heart"></i><%= posts.likes.count %>
          <% end %>
        <% end %>
        </p>
      <p><%= posts.text %></p>
      <p><%= link_to "#{posts.comments.count} コメント", post_path(posts) %></p>
      <% end %>
　</div>
　<div class="mb-5 tab-pane fade" id="like" role="tabpanel" aria-labelledby="like-tab">
      <% @likes.each do |like| %>
      <%= image_tag like.post.user.get_profile_image(90,90),class:"rounded-circle" %>
      <%= like.post.user.user_name %>
      <%= link_to post_path(like.post) do %>
      <p><%= image_tag like.post.get_image,size:"500x400" %></p>
      <% end %>
      <p><%= like.post.created_at.strftime('%Y.%m.%d') %></p>
      <p><%= like.post.text %></p>
      <% end %>
　</div>

app/views/user/users/unsubcrib.html.erb
<div class="container">
  <div class="justify-content-center">
    <h5>本当に退会しますか？</h5>
    <p>退会すると、会員登録情報や<br>
    　 これまでの購入履歴が閲覧できなくなります。<br>
    　 退会する場合は、「退会する」をクリックしてください。<br>
    </p>
    <%= link_to '退会しない',user_path(current_user),class:'btn btn-sm btn-primary' %>
    <%= link_to '退会する',user_withdraw_path,method: :patch,class:'btn btn-sm btn-danger' %>
  </div>
</div>

app/views/user/users/unsubscribe.html.erb
<div class="container">
  <div class="justify-content-center">
    <h5>本当に退会しますか？</h5>
    <p>退会すると、会員登録情報や<br>
    　 これまでの購入履歴が閲覧できなくなります。<br>
    　 退会する場合は、「退会する」をクリックしてください。<br>
    </p>
    <%= link_to '退会しない',user_path(current_user),class:'btn btn-sm btn-primary' %>
    <%= link_to '退会する',user_withdraw_path,method: :patch,class:'btn btn-sm btn-danger' %>
  </div>
</div>