config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  devise_for :user,path: 'patrie', controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}


  namespace :admin do
    root to:"homes#top"
    resources :posts
    resources :users
  end
  scope module: :user do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :posts do
      resources :comments, only: [:create,:destroy]
      resource :likes, only: [:create, :destroy]
    end
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    resources :notifications,only: [:index,:destroy]
    resources :relationships
    resources :users
    get "/user/unsubscribe" => "users#unsubscribe"
    patch "/user/withdraw" => "users#withdraw"
  end
  get '/search' => 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @posts = Post.looks(params[:search], params[:word])
    end
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  before_action :authenticate_user!
  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @posts = Post.looks(params[:search],params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path,local: true,method: :get do |f| %>
      <%= f.text_field :word,class: "rounded" %>
      <%= f.select :range,options_for_select([['User'],['Post']]) %>
      <%= f.select :search,options_for_select([["完全一致","perfect_match"],["前方一致","foward_match"],["後方一致","backword_mach"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索",class:"btn text-light" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h4>検索結果</h4>

<table class="table table-hovor table-inverse">
    <% if @range == "User" %>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td>
                <%= link_to user_path(user) do %>
                <%= image_tag user.get_profile_image(80,80) %>
                <% end %>
            </td>
            <td><%= link_to user_path(user) do %>
                <%= user.user_name %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
    <% else %>
    <tbody>
        <% @posts.each do |posts| %>
        <tr>
            <td><%= link_to post_path(posts) do %>
                <%= image_tag posts.user.get_profile_image(80,80) %>
                <% end %>
            </td>
            <td><%= link_to post_path(posts) do %>
                <%= posts.user.user_name %>
                <% end %>
            </td>
            <td><%= link_to post_path(posts) do %>
                <%= posts.text %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
    <% end %>
</table>